# Generated by Django 5.0.4 on 2024-06-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_rename_userprofile_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
