# Generated by Django 5.0.4 on 2024-06-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
